# Generated by Django 4.0.4 on 2022-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_relationship_profile_workingat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='follow_me',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_online',
            field=models.BooleanField(default=True),
        ),
    ]
