# Generated by Django 4.0.4 on 2022-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_allow_comments_profile_follow_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatart',
            field=models.ImageField(default='default.jpg', upload_to='avatars'),
        ),
    ]
